import type { agents as english } from "../en/agents";
type TranslationShape<T> = { [K in keyof T]: T[K] extends string ? string : TranslationShape<T[K]> };
export const agents: TranslationShape<typeof english> = {
  loading: "正在加载智能体", requestFailed: "Agent Core 请求失败。", searchPlaceholder: "按名称、模型或 ID 搜索…", searchLabel: "搜索智能体", refreshLabel: "刷新智能体", loadFailed: "无法加载智能体", refreshFailed: "无法刷新智能体", staleDescription: "上次加载的智能体配置仍然可用。", loadDescription: "Web 无法从已连接的 Agent Core 读取智能体配置。", connectionHint: "请检查侧栏中的 Agent Core 连接后重试。", openFailed: "无法打开最新智能体", retry: "重试", requestFailure: "请求失败",
  errors: {
    retrievalUnavailable: "此 Agent Core 连接不支持读取智能体。", interrupted: "智能体请求因连接变化而中断。", differentRetrieved: "Agent Core 返回了与请求不同的智能体。", updateUnavailable: "此 Agent Core 连接不支持更新智能体。", updateInterrupted: "智能体更新因连接变化而中断。", differentUpdated: "Agent Core 返回了与所更新对象不同的智能体。", deleteUnavailable: "此 Agent Core 连接不支持删除。", modelRequired: "请输入模型 ID。", nameTooLong: "名称最多 128 个字符。", metadataJson: "元数据必须是有效 JSON。", metadataObject: "元数据必须是 JSON 对象。", metadataStrings: "每个元数据值都必须是字符串。", metadataCount: "智能体元数据最多支持 16 组键值。", metadataLength: "元数据键最多 64 个字符，值最多 512 个字符。", reasoningDefault: "当前 Core 会话要求两个推理字段都使用 Core 默认值。", serviceTier: "当前 Core 会话仅支持 auto 服务层级。", textFormat: "当前 Core 会话仅支持文本格式。", verbosity: "低或高详细程度需要已发现的兼容 Codex 模型；此 Web 流程请使用 medium。", readOnlyTools: "此智能体包含只读的已保存工具定义，因此不能更改工具。", functionName: "每个 Function 都需要非空名称。", functionNameLength: "Function 名称最多 512 个 UTF-8 字节。", functionUnique: "Function 名称不能重复。", functionJson: "Function {{name}} 的参数必须是有效 JSON。", functionSchema: "Function {{name}} 的参数必须是 JSON 对象 schema。", mcpLabel: "每个 MCP 服务都需要非空标签。", mcpUnique: "MCP 服务标签不能重复。", mcpUrl: "MCP 服务 {{name}} 需要有效的匿名 HTTP(S) URL。", credentialMissing: "MCP 服务 {{name}} 引用了当前目录中不存在的凭据。", credentialUrl: "MCP 服务 {{name}} 必须使用所选凭据的精确 URL。", functionCount: "最多可配置 64 个 Function。",
  },
  catalog: {
    listLabel: "智能体", create: "创建智能体", createDescription: "描述希望智能体在运行时执行的任务。", untitled: "未命名智能体", editLabel: "编辑 {{name}}（{{id}}）", noInstructions: "尚无指令。", tools_one: "{{formattedCount}} 个工具", tools_other: "{{formattedCount}} 个工具", opening: "正在打开最新定义…", startLabel: "使用 {{name}}（{{id}}）启动会话", unavailable: "不可用", startSession: "启动会话", sessionUnavailable: "会话不可用：{{reason}}", showingAll: "正在显示全部 {{formattedCount}} 个已保存智能体", more_one: "还有 {{formattedCount}} 个已保存智能体", more_other: "还有 {{formattedCount}} 个已保存智能体", showLess: "收起", showMore: "再显示 {{formattedCount}} 个", noMatch: "没有匹配的智能体", noSaved: "没有已保存的智能体", trySearch: "请尝试其他名称、模型或 ID。", emptyHelp: "从空白智能体开始，或选择下方的入门模板。", clearSearch: "清除搜索", templates: "入门模板", templatesHelp: "仅提供提示词起点。请另行添加并验证工具。", templateList: "智能体入门模板", useTemplate: "使用{{name}}模板",
  },
  templates: {
    sre: { name: "事故响应 SRE 智能体", description: "根据提供的日志、手册、代码和部署历史调查事故。", instructions: "你是一名调查生产事故的 SRE 助手。帮助用户理解影响、确定可能原因并选择安全的下一步。\n\n明确受影响服务、症状、事故时间范围和客户影响。询问会实质影响调查的缺失信息。只使用对话中提供或已配置工具返回的证据。清楚区分事实、假设和未知项，优先进行只读诊断。提出会改变状态的操作前，说明其范围、风险、回滚方式和所需确认。输出简洁的事故摘要、证据、按置信度排序的可能原因、即时缓解措施和后续行动。" },
    slack: { name: "Slack AI 队友", description: "把提供的工作对话和文件转化为回答、分析和草稿。", instructions: "你是一名处理工作对话的 AI 队友。把用户或已配置工具提供的对话片段和内容转化为准确、实用的产出。总结决策、开放问题、负责人和截止日期；按要求的语气起草清晰回复；指出歧义或缺失上下文。除非对话中已提供或已配置工具返回相应内容，否则不要声称可以访问 Slack、频道、消息或文件。" },
    data: { name: "数据智能体", description: "使用提供的数据集或已配置工具调查业务问题。", instructions: "你是一名数据分析助手。在得出结论前，先明确业务定义、分析总体、指标和时间范围。只使用对话中提供或已配置工具返回的数据。展示重要计算或查询逻辑，区分观测事实与假设，并保留未知或缺失值。输出简洁答案、支持证据、限制条件和可复现的后续步骤。" },
    github: { name: "GitHub Issue 调查智能体", description: "追踪所提供缺陷报告的可能原因，并基于证据提出修复方案。", instructions: "你是一名软件问题调查助手。只使用用户提供的 Issue 文本、代码、日志、测试和工具结果。先复述实际行为、预期行为、范围和复现证据。追踪最可能原因，区分已确认的证据与假设，并提出带有聚焦测试的最小安全修复。除非已配置所需工具且用户明确要求，否则不要声称拥有仓库访问权限，也不要修改代码、分支、Issue 或拉取请求。" },
    invoices: { name: "批量发票与合同审查", description: "根据指定政策审查提供的文档批次并标记差异。", instructions: "你是一名文档审查助手。只审查对话中提供或已配置工具返回的发票、合同、政策和提取文本。将每份文档与用户指定规则比较，标记缺失字段和差异，在可用时引用支持文本，并在页面或数值不可读时保留不确定性。按文档输出结构化摘要，包含发现、严重程度、证据和后续问题。不要将审查表述为法律或财务建议。" },
  },
  form: {
    name: "名称", namePlaceholder: "仓库构建助手", nameHelp: "可选。Agent Core 最多接受 128 个 Unicode 字符。", instructions: "指令", instructionsPlaceholder: "描述此智能体应如何工作…", harness: "执行框架", coreStartup: "Core 启动配置", coreDefault: "{{name}} · Core 默认", notEnabled: "{{name}} · 未启用", noHarness: "未启用执行框架", harnessHelp: "只能选择此 Core 进程启动时启用的执行框架。选择结果不能证明运行时、provider 或模型已就绪。", model: "模型", webSuggestions: "Web 建议", configured: "已配置建议", default: "默认", previouslyUsed: "已保存智能体使用过", customModel: "自定义模型 ID…", modelHelp: "选择 Web 建议，或输入为你的运行时配置的 ID。", customModelLabel: "自定义模型 ID", modelFallback: "模型 ID", modelNote: "模型选项是可编辑的 Web 侧建议，不是从 Core 发现的目录。保存 {{model}} 不能证明当前 executor 可以运行它。", generation: "生成配置", advancedSettings: "高级已保存设置", compatibleDefaults: "兼容会话的默认值", textFormat: "文本格式", text: "文本", jsonPreserved: "JSON schema · 已保留", textFormatHelp: "当前由 Web 创建的会话使用文本。现有 JSON schema 会以只读方式保留，并阻止启动会话。", reasoningEffort: "推理强度", coreDefaultValue: "Core 默认", textVerbosity: "文本详细程度", reasoningSummary: "推理摘要", serviceTier: "服务层级", existingProfileHelp: "Agent Core 可以保存这些设置，但当前会话合约会拒绝显式推理、非 auto 服务层级和非文本格式。低或高详细程度还需要兼容的 Codex 模型。保存不兼容值会在此 Web 中禁用“启动会话”。", createProfileHelp: "创建时锁定为当前兼容会话的配置：文本格式、Core 默认推理、medium 详细程度和 auto 服务层级。Agent Core 可以存储其他值，但此 Web 目前无法用其中大多数配置启动会话。", tools: "工具", coreExecution: "仅由 Core 执行", functionBoundary: "Function 会让 Core 发出 function_call。外部应用或现有 Function 结果表单必须执行具体业务操作，并使用精确的 Turn 和调用标识提交 agent.session.input.tool_result。此 Web 不执行 Function。", mcpBoundary: "HTTP MCP 发现和调用在受信任的 Core 服务计算环境中运行。self_hosted 工作区可以运行 executor 命令，但 MCP 绝不会在此浏览器或该 executor 中运行。完整 Core 目录加载后，可以配置匿名及由凭据库静态 bearer 支持的 service-origin HTTP MCP。", readOnlyToolLabel: "只读的已保存工具", readOnlyTool: "只读的已保存工具", readOnlyHelp: "它会保持原样。此处不能启用或编辑 Web Search、Code Mode 命令/文件、凭据、OAuth、stdio、请求头及未知工具类型。", function: "Function", remove: "移除", description: "描述", descriptionPlaceholder: "查询客户记录", parameters: "参数 JSON Schema", parametersHelp: "必须是 JSON 对象。Function 始终为非延迟加载；最多允许 64 个名称唯一的 Function，每个名称最多 512 个 UTF-8 字节。", vaultMcp: "凭据库 bearer HTTP MCP", anonymousMcp: "匿名 HTTP MCP", serverLabel: "服务标签", authentication: "认证", anonymous: "匿名", selectedCredentialHelp: "所选凭据会确定并锁定精确的 MCP 目标。", catalogUnavailable: "凭据目录不可用，只能配置匿名 MCP。", serverUrl: "服务 URL", allowedTools: "允许的工具", allTools: "所有已公布工具", listedTools: "仅列出的工具", allowedToolsLabel: "{{name}} 允许的工具", mcpServer: "MCP 服务", allowedToolsHelp: "省略或 null 会允许所有已公布工具。空的列表值会序列化为空列表，即不允许任何工具。", required: "Core 执行必须使用此服务", mcpWriteHelp: "写入始终使用 transport.type=http 和 connection_origin=service。令牌由凭据库以只写方式管理，绝不会进入此表单。请求头、请求元数据、OAuth、stdio 和 client-origin 连接仍不受支持。", addFunction: "添加 Function", addMcp: "添加 HTTP MCP", metadata: "元数据", metadataHelp: "最多 16 组字符串键值的 JSON 对象；键最多 64 个字符，值最多 512 个字符。切勿在智能体元数据中保存密钥。",
  },
  setup: {
    requestPreview: "请求预览", previewHelp: "仅使用占位符。已连接 Core 的凭据绝不会读入此预览。", savedDefinition: "已保存定义", agentId: "智能体 ID", updated: "更新时间", multiAgent: "多智能体", enabledSaved: "已启用 · 已保存配置", disabled: "已禁用", guideTitle: "开始创建智能体", steps: { define: "定义智能体", defineHelp: "选择启动时启用的执行框架、模型和指令；Web 会将生成设置保持在当前会话安全配置。", save: "保存定义", saveHelp: "Core 将成为已保存智能体的持久事实来源。", start: "启动会话", startHelp: "选择支持的环境配置，创建空闲会话，并在发送输入前完成订阅。", exchange: "交换事件", exchangeHelp: "真实 Turn 仍需要兼容的 worker、executor、模型和 provider。" }, breadcrumb: "面包屑", newAgent: "新建智能体", sections: "智能体设置分区", setup: "设置", sessions: "会话", sessionsTitle: "会话历史可在“会话”产品视图中查看", definition: "智能体定义", updatedNotice: "智能体定义已更新。", savedNotice: "智能体定义已保存为 {{id}}。", readinessBoundary: "这不能证明执行已就绪。", startUnavailable: "无法启动会话。{{reason}}", back: "返回智能体", delete: "删除智能体", saving: "保存中…", saveChanges: "保存更改", saved: "智能体已保存", saveDefinition: "保存智能体定义", startSession: "启动会话",
  },
  details: {
    id: "ID", created: "创建时间", updated: "更新时间", model: "模型", name: "名称", instructions: "指令", metadata: "元数据", notSet: "未设置", none: "无", blocked: "此智能体可以保存，但已知的 Core 会话配置无法启动它：{{reason}}", runtimeBoundary: "已保存的高级配置不能证明运行时可用。模型、provider、主机、工具和条件性详细程度仍需 executor 验证。", advanced: "高级配置 · 只读", tools: "工具", reasoning: "推理", text: "文本", serviceTier: "服务层级", multiAgent: "多智能体", functionTool: "Function {{name}}", mcpTool: "{{auth}} 服务来源 HTTP MCP {{name}}", serviceOriginMcp: "服务来源 HTTP MCP", vaultBearer: "凭据库 bearer", anonymous: "匿名", readOnly: "{{label}} · 只读", deletePrompt: "从 Agent Core 删除 {{name}}？", deleteBefore: "从 Agent Core 删除", deleteAfter: "？", exactId: "精确智能体 ID：{{id}}", exactIdLabel: "精确智能体 ID：", deleteWarning: "只有在 Core 确认成功后才会移除已保存的智能体。现有会话会保留持久化的智能体快照。", deleteTitle: "删除智能体？", cancel: "取消", deleting: "删除中…",
  },
  savedTool: { malformed: "已保存的工具定义格式错误", toolSearch: "tool_search 仅可保存，不能在会话中运行", programmatic: "programmatic_tool_calling 仅可保存，不能在会话中运行", deferred: "延迟 Function 仅可保存", credentialedMcp: "当前凭据库目录中无法解析需要凭据的 MCP，或其 URL 不匹配", unsupportedFunction: "不支持的 Function 工具定义", unsupportedMcp: "不支持的 MCP 工具定义", unsupported: "不支持的已保存工具定义" },
  admission: { model: "模型不能为空", multiAgent: "不支持多智能体执行", reasoning: "显式推理选项仅可保存", serviceTier: "服务层级必须为 auto", text: "文本格式必须为 text", malformedTool: "已保存的工具配置不可执行", malformedFunction: "已保存的 Function 工具不完整或格式错误", deferred: "延迟 Function 仅可保存", functionName: "Function 名称必须非空且最多 512 字节", functionUnique: "Function 名称必须唯一", malformedMcp: "已保存的 MCP 工具不完整或格式错误", credential: "此 Web 会话流程无法使用附加的 MCP 凭据", mcpUnique: "MCP 服务标签必须唯一", savedOnly: "{{type}} 仅可保存", unsupportedTool: "已保存的工具类型不可执行", functionCount: "最多可执行 64 个 Function 工具", coreRequires: "当前 Core 会话准入要求：{{reasons}}。", vaultUnavailable: "无法附加会话凭据库。{{reason}}", managedMcp: "托管会话暂不支持 MCP 工具。请选择无环境或自托管环境，或使用仅含 Function 的智能体。" },
};
